MVCApp/Models/Department.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MVCApp.Models
{
    [Table("tblDepartment")]
    public class Department
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public List<Employee> Employees { get; set; }
    }
}

MVCApp/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MVCApp.Models
{
    [Table("tblEmployee")]
    public class Employee
    {
        public int EmployeeId { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string City { get; set; }
        public int DepartmentId { get; set; }
    }
}

MVCApp/Models/EmployeeContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace MVCApp.Models
{
    public class EmployeeContext :DbContext
    {
        public DbSet<Employee> Employees { get; set; }
        public DbSet<Department> Departments { get; set; }
    }
}

MVCApp/Controllers/DepartmentController.cs
using MVCApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCApp.Controllers
{
    public class DepartmentController : Controller
    {
        // GET: Department
        public ActionResult Index()
        {
            using (EmployeeContext employeeContext = new EmployeeContext())
            {
                List<Department> departments = employeeContext.Departments.ToList();
                return View(departments);
            }

        }
    }
}

MVCApp/Controllers/EmployeeController.cs
using MVCApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCApp.Controllers
{
    public class EmployeeController : Controller
    {

        //// GET: Employee
        //public ActionResult Index()
        //{
        //    using (EmployeeContext employee = new EmployeeContext())
        //    {
        //        List<Employee> empl = employee.Employees.ToList();
        //        return View(empl);
        //    }

        //}

        public ActionResult Index(int departmentId)
        {
            EmployeeContext employeeContext = new EmployeeContext();
            List<Employee> employees = employeeContext.Employees.Where(emp => emp.DepartmentId == departmentId).ToList();

            return View(employees);
        }


        // GET: Employee
        public ActionResult Details(int id)
        {
            using (EmployeeContext employee=new EmployeeContext())
            {
                Employee empl= employee.Employees.Single(x=> x.EmployeeId==id);
                return View(empl);
            }
           
        }
    }
}

MVCApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewData["Countries"] = new List<string>()
            {
                "India",
                "Argentina"
            };
            return View();
        }

        //public string Index()
        //{
        //    return typeof(Controller).Assembly.GetName().Version.ToString();
        //}
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MVCApp/Views/Department/Index.cshtml
@using MVCApp.Models;
@model  IEnumerable<Department>

@{
    ViewBag.Title = "Department List";
}

<div style="font-family:Arial">
    <h2>Department List</h2>

    <ul>
        @foreach (Department department in @Model)
        {
            <li>
                @Html.ActionLink(department.Name, "Index", "Employee",
                 new { departmentId = department.ID }, null)
           </li>
        }
    </ul>
</div>

MVCApp/Views/Employee/Details.cshtml
@model MVCApp.Models.Employee
@{
    ViewBag.Title = "ED";
}
<div style="font-family:Arial">
    <h2>Employee Details</h2>

    <table>
        <tr>
            <td>
                Employee ID:
            </td>
            <td>
                @Model.EmployeeId
            </td>
        </tr>
        <tr>
            <td>
                Name:
            </td>
            <td>
                @Model.Name
            </td>
        </tr>
        <tr>
            <td>
                Gender:
            </td>
            <td>
                @Model.Gender
            </td>
        </tr>
        <tr>
            <td>
                City:
            </td>
            <td>
                @Model.City
            </td>
        </tr>
    </table>
    @*@Html.ActionLink("Back", "Index")*@
    @Html.ActionLink("Back to Employee List", "Index", new { departmentId = @Model.DepartmentId })
</div>

MVCApp/Views/Employee/Index.cshtml
@model IEnumerable<MVCApp.Models.Employee>
@using MVCApp.Models;
@{
    ViewBag.Title = "Employee List";
}
<div style="font-family:Arial">
    <h2>Employee List</h2>
    <ul>
        @foreach (Employee emp in @Model)
        {
            <li>
                @Html.ActionLink(emp.Name, "Details", new { @id = emp.EmployeeId })
            </li>
        }

    </ul>
    @Html.ActionLink("Back to Department List", "Index", "Department")
</div>

MVCApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MVCApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MVCApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Countries List";
}

<h2>Countries List</h2>

<ul>

    @foreach (string strCountry in (List<string>)ViewData["Countries"])
    {
        <li>@strCountry</li>
    }

</ul>

@*<div class="jumbotron">
        <h1>ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
    </div>

    <div class="row">
        <div class="col-md-4">
            <h2>Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </div>
    </div>*@

MVCApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>